config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'profiles#index'
  resources :profiles, except: :index
  resources :profile_skills, only: [:new, :create] do
  end
  get 'search', to: 'profiles#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user


  has_many :profile_skills
  has_many :skills, through: :profile_skills
  mount_uploader :photo, PhotoUploader
  include PgSearch::Model
    multisearchable against: [:email, :full_name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/profile_skill.rb
class ProfileSkill < ApplicationRecord
  belongs_to :profile
  belongs_to :skill

  validates :skill, presence: true

  validates :experience, presence: true, inclusion: { in: (0..5) },
                     numericality: { only_integer: true }

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :profile_skills


  has_many :profiles, through: :profile_skills



  include PgSearch::Model
  multisearchable against: [:title]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile


  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profile_skills_controller.rb
class ProfileSkillsController < ApplicationController
  def new
    @profile_skill = ProfileSkill.new
  end

  def create
    unless Skill.find_by(title: params[:profile_skill][:skill])
      skill = Skill.create(title: params[:profile_skill][:skill])
    else
      skill = Skill.find_by(title: params[:profile_skill][:skill])
    end
    @profile_skill = ProfileSkill.new(experience: params[:profile_skill][:experience], profile: current_user.profile)
    @profile_skill.skill = skill
    if @profile_skill.save
      redirect_to profile_path(current_user.profile)
    else
      render :new
    end


  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    if current_user.profile
      @profiles = Profile.all
    else
      redirect_to new_profile_path
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def search
    results = PgSearch.multisearch(params[:query])
    @profiles = []
    results.each do |result|
      if result.searchable.class.to_s == "Skill"
      result.searchable.profiles.each do |profile|
        @profiles << profile
      end
      else
      @profiles << result.searchable
      end
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    profile = Profile.new(profile_params)
    profile.email = current_user.email
    profile.user = current_user
    profile.save


    redirect_to root_path
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)

    redirect_to profile_path(@profile)
  end


  private


  def profile_params
  params.require(:profile).permit(:full_name, :current_role, :description, :github_username, :slack_username, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Network</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profile_skills/new.html.erb
<div class="col-8">
  <h1>Add a skill:</h1>
  <%= simple_form_for (@profile_skill) do |f| %>
  <%= f.input :experience %>
  <%= f.input :skill %>
  <%= f.submit "Make skill", class: "btn btn-primary btn-block mb-5" %>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<div class="col-8">
  <%= simple_form_for (profile) do |f| %>
  <%= f.input :full_name %>
  <%= f.input :current_role %>
  <%= f.input :description %>
  <%= f.input :github_username %>
  <%= f.input :slack_username %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Finish Profile", class: "btn btn-primary btn-block mb-5" %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<h1 class="text-center">Edit Your Profile:</h1>
<div class="container d-flex justify-content-center" style="height: 85vh">
<%= render "form", profile: @profile  %>
</div>

app/views/profiles/index.html.erb
<div class="container mt-5">
  <%= form_tag search_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a profile"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
  <div class="grid">
    <div class="row">
      <% @profiles.each do |profile| %>
        <div class="col-6">
          <%= link_to profile_path(profile)  do%>
            <div class="card-profile m-2">
              <% if profile.photo %>
                <%= cl_image_tag profile.photo, height: 300, width: 400, crop: :fill %>

              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
              <% end %>
              <div class="card-profile-infos">
                <h2><%= profile.full_name %></h2>
                <p> <%= profile.current_role %> </p>
                <p> <%= profile.description %> </p>
                <p> <%= profile.slack_username %> </p>
                <p> <%= profile.github_username %> </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1 class="text-center">Make Your Profile:</h1>
<div class="container d-flex justify-content-center" style="height: 85vh">
<%= render "form", profile: @profile  %>
</div>

app/views/profiles/search.html.erb
<div class="container mt-5">
  <%= form_tag search_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a profile"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
  <div class="grid">
    <div class="row">
      <% @profiles.each do |profile| %>
        <%= link_to profile_path(profile)  do%>
          <div class="card-profile m-2">
            <% if profile.photo %>
              <%= cl_image_tag profile.photo, height: 300, width: 400, crop: :fill %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
              <div class="card-profile-infos">
              <h2><%= profile.full_name %></h2>
              <p> <%= profile.current_role %> </p>
              <p> <%= profile.description %> </p>
              <p> <%= profile.slack_username %> </p>
              <p> <%= profile.github_username %> </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container mt-3">


  <% if @profile == current_user.profile %>
    <div class="d-flex justify-content-center">
      <h1 class="text-center"> Your Profile </h1>
      <%= cl_image_tag current_user.profile.photo, class: 'avatar' %>
    </div>
    <div class="d-flex justify-content-between mb-5">
      <%= link_to 'Add a skill', new_profile_skill_path, class: "btn btn-primary" %>
      <%= link_to 'Edit my profile', edit_profile_path(current_user.profile), class: "btn btn-primary" %>
    </div>
  <% else %>
    <h1 class="text-center"><%= @profile.full_name %></h1>
  <% end %>
  <div class="d-flex justify-content-around">
    <div>
      <h2 class="border-bottom">Profile Description</h2>
      <p><%= @profile.description %></p>
    </div>
    <div>
      <h2 class="border-bottom">Skills:</h2>
      <ul>
        <% @profile.profile_skills.each do |profile_skill| %>
          <li><%= profile_skill.skill.title %> - <%= profile_skill.experience %></li>
        <% end  %>
      </ul>
    </div>
  </div>
  <div class="mt-5 text-center">

    <p><i class="fab fa-slack"> Find me on slack: </i> @<%= @profile.slack_username %></p>
    <%= link_to "https://github.com/#{@profile.github_username}"  do%>
    <i class="fab fa-github"></i> <%= @profile.github_username %>
    <% end %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://middle.pngfans.com/20190501/ua/profile-white-icon-png-computer-icons-user-profile-ee6176836f66e99c.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
           <% unless current_user %>
              <%= cl_image_tag current_user.profile.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://icon-library.net/images/google-user-icon/google-user-icon-11.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if  current_user.profile%>
            <%= link_to "My profile", profile_path(current_user.profile), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>